### ISSUE TITLE
Uncaught ReferenceError: File is not defined

### ISSUE THREAD

**Issue by ander7agar** [darrachequesne/has-binary#5]
It seems that the new version (1.0.3) causes the following error in the engine.io-parser library:

```
/home/myUser/WebstormProjects/myApp/node_modules/has-binary2/index.js:12 Uncaught ReferenceError: File is not defined
    at Object.<anonymous> (/home/myUser/WebstormProjects/myApp/node_modules/has-binary2/index.js:12:22)
    at Object.<anonymous> (/home/myUser/WebstormProjects/myApp/node_modules/has-binary2/index.js:66:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/myUser/WebstormProjects/myApp/node_modules/engine.io-parser/lib/index.js:6:17)
    at Object.<anonymous> (/home/myUser/WebstormProjects/myApp/node_modules/engine.io-parser/lib/index.js:482:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```
This error I have obtained when I have reinstalled the libraries of my application.

**Comment by darrachequesne** [comment]
@ander7agar it seems https://github.com/darrachequesne/has-binary/pull/4 has some side-effects..

The tests seems to pass in CI though (https://travis-ci.org/socketio/engine.io/jobs/379150554), which version of Node.js are you using?

**Comment by ander7agar** [comment]
I am using `electron@2.0.0`  and `node@8.9.0` to make my application.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
